options:
    limit_rows: True  # spécifie s'il faut lire uniquement le premier `` max_rows '' de chaque csv
    max_rows: 100000 # définir le nombre de lignes à lire de chaque fichier CSV car la lecture> 3 Go va prendre une éternité
                     # quand `` bound_lon '' ou `` bound_lat`` est vrai, les limites sont lues à partir de `` grid_params``
    bound_lon: False # spécifie s'il faut utiliser les limites de longitude fixes spécifiées au lieu de les déduire
    bound_lat: True  # spécifie s'il faut utiliser les limites de latitude rigides spécifiées au lieu de les inférer
                     # quand `` bound_time`` est vrai, les limites sont lues à partir de `` meta_params``
    bound_time: True # spécifie s'il faut lier les temps considérés
    interp_actions: True # spécifie s'il faut interpoler les actions si les transitions d'état ne sont pas adjacentes, sinon les actions peuvent être arbitrairement grandes
    allow_diag: True # lorsque interp_actions est vrai, spécifie s'il faut autoriser les actions de grille diagonale ou non
    append_coords: True # spécifie s'il faut ajouter des valeurs brutes de latitude et de longitude en tant que colonnes au csv de sortie
    prec_coords: 3 # le nombre de décimales pour arrondir chaque coordonnée à
    min_states: 2 # définir le nombre minimum d'états dans une trajectoire nécessaire pour la qualifier pour le fichier de sortie

directories:
    in_dir_path: ais_parser/ # spécifie le répertoire où se trouvent les données d'entrée
    in_dir_data: /aiscsv/ # spécifie le nom du dossier contenant toutes les données du répertoire d'entrée
    out_dir_path: ais_parser/filtered_data_for_visualisations/ # spécifie le répertoire dans lequel les fichiers de données de sortie doivent être écrits
    out_dir_file: ais_data_output.csv # spécifie le nom du fichier de sortie (doit être .csv)

# spécifie les limites des métadonnées (incluses) pour les données à prendre en compte
# limites de temps vont de min_year / min_month à max_year / max_month, pas seulement une plage de mois de chaque année valide
meta_params:
    # la première heure (incluse) qui sera prise en compte
    # données disponibles jusqu'en janvier 2020
    min_year: 2020
    min_month: 1
    # la dernière heure (incluse) qui sera prise en compte
    # données disponibles jusqu'en décembre 2020
    max_année: 2021
    mois_max: 12

    min_day: 1
    max_day: 30

# cela suivra les latitudes et longitudes minimales et maximales dans le jeu de données si bound_lat et bound_lon sont False
# sinon, grid_params spécifie les limites de la grille en degrés.
grid_params:
    min_lon: -78.0 # la longitude minimale qui sera considérée
    max_lon: -72.0 # la longitude maximale qui sera considérée
    min_lat: 25.0 # la latitude minimale qui sera considérée
    max_lat: 50.0 # la latitude maximale qui sera considérée
    num_cols: 0 # le nombre de colonnes dans la grille finale, qui sera automatiquement calculé par le script
    grid_len: 0,5 # la longueur d'un côté d'un carré de la grille, en degrés

